var GAME_LEVELS = [
  ["                                                                                    ",
   "  xxxxxxxxxxxxxxxxxxxxxxx                                    x                      ",
   "  x          k          x                                    x                      ",
   "  x                     x                                    x                      ",
   "  xxxxxxxxxxxxxxxxxxxxxxx                                    x                      ",
   "                                                             x                      ",
   "                                                            !x!                     ",
   "                                                            !x!                     ",
   "                                                            !x!                     ",
   "                                                            !x!                     ",
   "                                                            !x!                     ",
   "                                                            !x!                     ",
   "                                                            !x!            xxxxxxxxx",
   "                                                            !x!            xxxxxxxxx",
   "   xx           yyy        yyy      yyy       yyy           !x!            xxxxxxxxx",
   "   xx            |          |        |         |            !x!            xxxxxxxxx",
   "   xx                                                       !x!            xxxxxxxxx",
   "   xx                                                       !x!            xxxxxxxxx",
   "   xx                                                       !x!            xxxxxxxxx",
   "   xx        s         o         o         o         o       !             xxxxxxxxx",
   "   xx    @                                                   v         ~   xxxxxxxxx",
   "   xxxxxxxxxxxx     xxxxx     xxxxx     xxxxx     xxxxx            xxxxxxxxxxxxxxxxx",
   "   xxxxxxxxxxxx!!!!!xxxxx!!!!!xxxxx!!!!!xxxxx!!!!!xxxxx            xxxxxxxxxxxxxxxxx",
   "   xxxxxxxxxxxx!!!!!xxxxx!!!!!xxxxx!!!!!xxxxx!!!!!xxxxx            xxxxxxxxxxxxxxxxx",
   "   xxxxxxxxxxxx!!!!!xxxxx!!!!!xxxxx!!!!!xxxxx!!!!!xxxxx            xxxxxxxxxxxxxxxxx",
   "   xxxxxxxxxxxx!!!!!xxxxx!!!!!xxxxx!!!!!xxxxx!!!!!xxxxx            xxxxxxxxxxxxxxxxx",
   "   xxxxxxxxxxxx!!!!!xxxxx!!!!!xxxxx!!!!!xxxxx!!!!!xxxxx            xxxxxxxxxxxxxxxxx",
   "   xxxxxxxxxxxx!!!!!xxxxx!!!!!xxxxx!!!!!xxxxx!!!!!xxxxx            xxxxxxxxxxxxxxxxx",
   "   xxxxxxxxxxxx!!!!!xxxxx!!!!!xxxxx!!!!!xxxxx!!!!!xxxxx            xxxxxxxxxxxxxxxxx",
   "   xxxxxxxxxxxx!!!!!xxxxx!!!!!xxxxx!!!!!xxxxx!!!!!xxxxx      j     xxxxxxxxxxxxxxxxx",
   "   xxxxxxxxxxxx!!!!!xxxxx!!!!!xxxxx!!!!!xxxxx!!!!!xxxxx            xxxxxxxxxxxxxxxxx",
   "   xxxxxxxxxxxx!!!!!xxxxx!!!!!xxxxx!!!!!xxxxx!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                          x                                         "],
  ["     xxxxxxxx                             x                                         ",
   "     xx    xx                             x          o                              ",
   "     xx                                   x                                         ",
   "     xx @                                 x   h    xxxx                             ",
   "     xxxxx                                xo       x                                ",
   "                         o                x        x      o                         ",
   "            yyy                           xx       x     yyy                        ",
   "    x=                  yyy               x!       x                                ",
   "             o                            xv       x                                ",
   "    x       =                    =x       x        x         o                      ",
   "                  yyy                     x   h   ox        yyy  o                  ",
   "    x=       o           = x  o           x        x                                ",
   "                   o                      x       xx               o                ",
   "            yyy                  =x       x       !x                                ",
   "                       yyy                x       vx                                ",
   "    x=           o                x       x        x               o                ",
   "                         o                x        x                                ",
   "                yyy                       x   h    x                                ",
   "                     xxxxxxxxxxxxx                 x               k                ",
   "!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxx         j    x            xxxxxxx             ",
   "!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxx           x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
     ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  !      !                     !                                           ",
   "    xxxxxxxxx    xxxxxxxxxxxxxxx     !      v                     !                   xxxxxxxxxxx             ",
   "      xxxxx       xxxxxxxxxxxxx      !                @           v                   x         x             ",
   "      xxxxx        xxxxxxxxxxx       v                                                x    k    x             ",
   "       xxx          xxxxxxxxx                                                                                 ",
   "       xxx           xxxxxxx                          o                                  xxxxx                ",
   "        x             xxxxx                                                        x            xx   h        ",
   "        x              xxx                                                          xxx             xx        ",
   "                        x                                                                 xxxxx               ",
   "                        x                                  x                                           xxx    ",
   "                                                      o    x                        xxxx    h                 ",
   "                                        x                  x                                  xxxx            ",
   "                                       xx                  x                                        xxxx      ",
   "                                     xxxxxxxxxxx           x                           xxxx                   ",
   "                                       xx                  x                                                 ",
   "         x                              x            o     x                                                  ",
   "         x                                                 x                           xxx          xxxx      ",
   "         x                               o            s    x                         xx       j               ",
   "         x  xxxx            o      xxxxxxxxxxxxxxxxxxxxxxxxx               !       xx        xxx              ",
   "         x                xxxxx                                                   x                           ",
   "         x        k                                                        |     x = o     =  =  =   y        ",
   "         x      xxxxx                                                             x                    x     ",
   "         x                                  xxxxxx            yyy                  xx      xxxx       xxx    ",
   "         x                            !                o                             xx              xxxxx    ",
   "         xxxxxxxxxxxxxxxx      s                                                       xxx             x      ",
   "                        xxxxxxxxxx                   xxx       o                         xxxx          x      ",
   "                                 x                                      xxx                            x     ",
   "                                 x                    o        xxx          !                    xxxxx        ",
   "                    x            x    | xxxxxx                                                               ",
   "                    xx           x                    s                              x                       ",
   "              xxxxxxxxxx         x                   xxx                     s                               ",
   "                    xx           x                                       xxxxxxxx            j                 ",
   "                    x            x    |                        xxxx                        xxxxx              ",
   "                                 x                                                                            ",
   "                                 xxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxx        xxxxx                    ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
["                                    ",
    "                                 ",
    "                                 ",
    "  x     x   xxx     x      x     ",
    "   x   x   x   x    x      x     ",
    "    x x   x     x   x      x     ",
    "     x   x   @   x  x      x     ",
    "     x    x     x   x      x     ",
    "     x     x   x     x    x      ",
    "     x      xxx       xxxx       ",
	"                                 ",
    " x         x  xx   x    x   x    ",
    " x         x x  x  xx   x   x    ",
    "  x       x x    x x x  x   x    ",
    "  x   x   x x    x x  x x   x    ",
    "   x x x x   x  x  x   xx        ",
    "    x   x     xx   x    x   x    ",
    "                                 ",
    "                                 ",
    "                                 "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
